INSERT INTO T_ITEMS_CATEGORY(CATEGORY_ID, CATEGORY_NAME)
  VALUES('100', '普通商品');
INSERT INTO T_ITEMS_CATEGORY(CATEGORY_ID, CATEGORY_NAME)
  VALUES('101', '话费');
INSERT INTO T_ITEMS_CATEGORY(CATEGORY_ID, CATEGORY_NAME)
  VALUES('102', '电影');
INSERT INTO T_ITEMS_CATEGORY(CATEGORY_ID, CATEGORY_NAME)
  VALUES('103', '餐饮');
INSERT INTO T_ITEMS_CATEGORY(CATEGORY_ID, CATEGORY_NAME)
  VALUES('104', '酒店');
INSERT INTO T_ITEMS_CATEGORY(CATEGORY_ID, CATEGORY_NAME)
  VALUES('105', 'KTV');
INSERT INTO T_ITEMS_CATEGORY(CATEGORY_ID, CATEGORY_NAME)
  VALUES('300', '技能商品');

